# Generated by Django 3.0.4 on 2020-03-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_contact', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('list_no', models.IntegerField()),
                ('sub_list_no', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('wechat', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('invoice_no', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('dimensions', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('customer_amount', models.IntegerField()),
                ('customer_amount_after_discount', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('actual_vendor_amount', models.IntegerField()),
                ('vendor_deposit_persentage', models.IntegerField()),
                ('vendor_advance_deposit_amount', models.IntegerField()),
                ('token_deposit_customer', models.IntegerField()),
                ('token_deposit_HSTC', models.IntegerField()),
                ('token_deposit_date', models.DateField()),
                ('vendor_advance_balance', models.IntegerField()),
                ('vendor_advance_balance_paid', models.IntegerField()),
                ('advance_balance_date', models.DateField()),
                ('vendor_final_balance', models.IntegerField()),
                ('vendor_final_balance_date', models.DateField()),
                ('account_details', models.CharField(max_length=200)),
                ('manufacturing_days', models.IntegerField()),
                ('CBM_m3', models.IntegerField()),
                ('ctns', models.IntegerField()),
                ('gross_weight_kgs', models.IntegerField()),
                ('net_weight_kgs', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_inspection_date', models.DateField()),
                ('actual_inspection_date', models.DateField()),
                ('inspection_done_by', models.CharField(max_length=300)),
                ('inspection_remarks', models.CharField(max_length=300)),
                ('inspection_photo_1', models.ImageField(upload_to='')),
                ('inspection_photo_2', models.ImageField(upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('vendor_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_PI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('list_no', models.IntegerField()),
                ('sub_list_no', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('dimensions', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=100)),
                ('unit_Price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('customer_amount', models.IntegerField()),
                ('customer_amount_after_discount', models.IntegerField()),
                ('token_deposit_customer', models.IntegerField()),
                ('token_deposit_HSTC', models.IntegerField()),
                ('token_deposit_date', models.DateField()),
                ('CBM_m3', models.IntegerField()),
                ('ctns', models.IntegerField()),
                ('gross_weight_kgs', models.IntegerField()),
                ('net_weight_kgs', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
