# Generated by Django 3.0.4 on 2020-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shipment_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
