# Generated by Django 3.0.4 on 2020-04-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_shipment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container_loading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('PortDetails1', models.CharField(blank=True, max_length=200, null=True)),
                ('PortDetails2', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('vendor_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer_Details')),
            ],
        ),
    ]
